version: '3'

services:
  db:
    image: postgres:11
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:5.0
    command: redis-server
    volumes:
      - redis:/data

  app: &app_base
    build:
      context: ../masajid
      dockerfile: Dockerfile.prod
    env_file: .env
    volumes:
      - storage:/app/web_container/storage
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis

  sidekiq:
    <<: *app_base
    command: bundle exec sidekiq -C config/sidekiq.yml
    ports: []
    depends_on:
      - app

  cron_job:
    <<: *app_base
    command: cron -f
    ports: []
    depends_on:
      - app

  nginx:
    build:
      context: nginx
    ports:
      - 80:80
      - 443:443

volumes:
  redis:
  db-data:
  storage:
