version: '3'

services:
  db:
    image: postgres:11
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:5.0
    command: redis-server
    volumes:
      - redis:/data

  sidekiq:
    build:
      context: ../masajid/
      dockerfile: Dockerfile.prod
    env_file: .env
    command: sidekiq -C config/sidekiq.yml
    volumes:
      - storage:/app/web_container/storage
    depends_on:
      - db
      - redis

  cron_job:
    build:
      context: ../masajid/
      dockerfile: Dockerfile.prod
    env_file: .env
    command: cron -f
    volumes:
      - storage:/app/web_container/storage
    depends_on:
      - db
      - redis

  app:
    build:
      context: ../masajid/
      dockerfile: Dockerfile.prod
    env_file: .env
    volumes:
      - storage:/app/web_container/storage
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis

  nginx:
    build:
      context: nginx
    ports:
      - 80:80
      - 443:443

volumes:
  redis:
  db-data:
  storage:
